### ISSUE TITLE
FirebaseError: Firebase: Error (auth/invalid-api-key).

### ISSUE THREAD

**Issue by TinsFox** [Sam-Apostel/confessions#33]
**Describe the bug**

**To Reproduce**
Just clone this repo and run those commands:
1. npm i
2. npm run dev

**Expected behavior**
I want to visit this site normally

**Screenshots**
<img width="1073" alt="image" src="https://user-images.githubusercontent.com/33956589/197708657-e891cdba-0ea7-432c-84fb-9fe6f4acbcaf.png">

**Desktop (please complete the following information):**
 - OS: macOS  
 - Browser: chrome
 - Version: Latest

**Additional context**
I hope to learn how to use satori through this project, thinks!

**Comment by Sam-Apostel** [comment]
Hi, TinsFox

This project needs firebase to run. The setup is probably not worth it for just learning satori.
I don't use satori directly but use the @vercel/og package (that depends on satori).

# My setup
## /pages/api/og.tsx
Construct the open graph image based on the searchParams from the request

## /components/head/head.js (Lines 24 - 27)
Define the open graph image based on props passed to the custom Head component

## /pages/confessions/[id].js
Server side fetch data for page and open graph image
Call the custom Head component

You can use this setup in any up to date next.js app.

Good luck!

**Comment by TinsFox** [comment]
Thanks a lot, Sam-Apostel
